#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from bigimg import main, lossless_random
import argparse

def setup_parser():
    desc = "Script for generating large images."
    parser = argparse.ArgumentParser(description=desc)
    parser.add_argument('w', nargs='?', metavar='w', help="width")
    parser.add_argument('h', nargs='?', metavar='h', help="height")
    parser.add_argument('o', nargs='?', metavar='o', help="output file")
    parser.add_argument('--lambda', dest='fs', default="random",
                    help='Specify a name ')
    return parser.parse_args()

if __name__ == "__main__":
    args = setup_parser()
    if args.w and args.h and args.o:
        if args.fs == 'random':
            lossless_random(args.w, args.h, args.fs, args.o)
        else:
            main(args.w, args.h, args.fs, args.o)
